[[colors.indexed_colors]]
color      = "#ff966c"
index      = 16

[[colors.indexed_colors]]
color      = "#c53b53"
index      = 17

[colors.bright]
black    = "#444a73"
red      = "#ff757f"
green    = "#c3e88d"
yellow   = "#ffc777"
blue     = "#82aaff"
magenta  = "#c099ff"
cyan     = "#86e1fc"
white    = "#c8d3f5"

[colors.normal]
black    = "#1b1d2b"
red      = "#ff757f"
green    = "#c3e88d"
yellow   = "#ffc777"
blue     = "#82aaff"
magenta  = "#c099ff"
cyan     = "#86e1fc"
white    = "#828bb8"

[colors.primary]
background = "#000000"
foreground = "#c8d3f5"

[env]
TERM = "xterm-256color"

[font.normal]
family = "JetBrainsMono NerdFont"

# [terminal.shell]
# program = "tmux"

[[keyboard.bindings]]
key = "Return"
mods = "Control"
chars = "\u001b[13;5u"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[13;2u"
