format = """
$battery\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$c\
$cmake\
$python\
$rust\
$nix_shell\
$env_var\
$sudo\
$status\
$os\
$shell\
$character"""

add_newline = false

[directory]
style = "blue bold"

[python]
style = "yellow bold"
format = "[${symbol}$virtualenv ]($style)"
symbol = " "

[rust]
style = "red bold"
format = "[${symbol}]($style)"

[[battery.display]]
threshold = 25
style = 'bold red'
discharging_symbol = " "

