format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$c\
$cmake\
$python\
$rust\
$nix_shell\
$env_var\
$sudo\
$battery\
$time\
$status\
$os\
$shell\
$character"""
