format = """
${time}\
${custom.mailerr}\
${custom.mail}\
${custom.todo}\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$c\
$cmake\
$python\
$rust\
$nix_shell\
$env_var\
$sudo\
$battery\
$status\
$os\
$shell\
$character"""

[time]
disabled = false
style = "white dimmed"
format = "[󱑎 $time ]($style)"
time_format = '%H:%M'

[python]
style = "yellow bold"
format = "[${symbol}$virtualenv ]($style)"
symbol = " "

[custom.mail]
style = "dimmed white"
symbol = "󰇮"
command = "grep '[^[:space:]]'  ~/mail/unread"
when = "test -s ~/mail/unread"
format = "[$symbol $output ]($style)"

[custom.mailerr]
style = "red"
symbol = ""
when = "test -s ~/mail/errors"
format = "[$symbol  ]($style)"

[custom.todo]
detect_files = ["TODO.md"]
style = "dimmed white"
symbol = ""
command = "todo_summary"
format = "[$symbol $output ]($style)"
