format = """
${custom.mailerr}\
${custom.mail}\
${custom.todo}\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$c\
$cmake\
$python\
$rust\
$nix_shell\
$env_var\
$sudo\
$battery\
$time\
$status\
$os\
$shell\
$character"""

[python]
symbol = " "

[custom.mail]
style = "yellow"
symbol = "󰇮"
command = "grep '[^[:space:]]'  ~/mail/unread"
when = "test -s ~/mail/unread"
format = "[$symbol $output ]($style)"

[custom.mailerr]
style = "red"
symbol = ""
when = "test -s ~/mail/errors"
format = "[$symbol  ]($style)"

[custom.todo]
detect_files = ["TODO", "TODO.md"]
style = "purple"
symbol = ""
command = "todo_summary"
format = "[$symbol $output ]($style)"
