# make colors inside tmux look the same as outside of tmux
# see https://github.com/tmux/tmux/issues/696
# see https://stackoverflow.com/a/41786092
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# for images
set -gq allow-passthrough on

set -g mouse                  # enable mouse
set -g base-index 1           # number windows with 1
set -g renumber-windows       # renumber when closing

# Main status bar colors (Mocha Crust/Mantle backgrounds)
set -g status-style bg="#11111b",fg="#cdd6f4"
# set -g status-left-length 30
# set -g status-right-length 50

# color theme
# set -g status-left "#[fg=#1e1e2e,bg=#89b4fa,bold]#{?SSH_CONNECTION,  #H ,}#(~/.config/tmux/wg-status.sh)#[bg=#11111b,fg=#89b4fa]"
set -g status-left ""
set -g status-right "#[fg=#1e1e2e,bg=#89b4fa,bold]#{?SSH_CONNECTION,  #H ,}#(~/.config/tmux/wg-status.sh)#[bg=#11111b,fg=#89b4fa]#[fg=#b4befe,bg=#11111b]#[fg=#1e1e2e,bg=#b4befe,bold] %d.%m %H:%M "
setw -g window-status-separator ""
setw -g window-status-format "#[fg=#313244,bg=#45475a]#[fg=#cdd6f4,bg=#45475a] #I #[fg=#313244,bg=#45475a]#[fg=#a6adc8,bg=#313244] #W #[fg=#313244,bg=#11111b]"
setw -g window-status-current-format "#[fg=#45475a,bg=#cba6f7]#[fg=#11111b,bg=#cba6f7,bold] #I #[fg=#45475a,bg=#cba6f7]#[fg=#cdd6f4,bg=#45475a,bold] #W #[fg=#45475a,bg=#11111b]"
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour81

# rebind to keep the cwd
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Navigate panes with Vim keys without prefix (M = Alt)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# setw -q -g utf8 on

# reload configuration
bind r run '"$TMUX_PROGRAM" ${TMUX_SOCKET:+-S "$TMUX_SOCKET"} source "$TMUX_CONF"' \; display "#{TMUX_CONF} sourced"

# copy to global buffer
if -b 'command -v xsel > /dev/null 2>&1' 'bind y run -b "\"\$TMUX_PROGRAM\" \${TMUX_SOCKET:+-S \"\$TMUX_SOCKET\"} save-buffer - | xsel -i -b"'
if -b '! command -v xsel > /dev/null 2>&1 && command -v xclip > /dev/null 2>&1' 'bind y run -b "\"\$TMUX_PROGRAM\" \${TMUX_SOCKET:+-S \"\$TMUX_SOCKET\"} save-buffer - | xclip -i -selection clipboard >/dev/null 2>&1"'
# copy to Wayland clipboard
if -b 'command -v wl-copy > /dev/null 2>&1' 'bind y run -b "\"\$TMUX_PROGRAM\" \${TMUX_SOCKET:+-S \"\$TMUX_SOCKET\"} save-buffer - | wl-copy"'
# copy to macOS clipboard
if -b 'command -v pbcopy > /dev/null 2>&1' 'bind y run -b "\"\$TMUX_PROGRAM\" \${TMUX_SOCKET:+-S \"\$TMUX_SOCKET\"} save-buffer - | pbcopy"'
if -b 'command -v reattach-to-user-namespace > /dev/null 2>&1' 'bind y run -b "\"\$TMUX_PROGRAM\" \${TMUX_SOCKET:+-S \"\$TMUX_SOCKET\"} save-buffer - | reattach-to-usernamespace pbcopy"'
# copy to Windows clipboard
if -b 'command -v clip.exe > /dev/null 2>&1' 'bind y run -b "\"\$TMUX_PROGRAM\" \${TMUX_SOCKET:+-S \"\$TMUX_SOCKET\"} save-buffer - | clip.exe"'
if -b '[ -c /dev/clipboard ]' 'bind y run -b "\"\$TMUX_PROGRAM\" \${TMUX_SOCKET:+-S \"\$TMUX_SOCKET\"} save-buffer - > /dev/clipboard"'

